<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

final class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * Permission name suffixes (ResourceName portion) as generated by
     * `php artisan shield:generate --all --panel=admin`.
     *
     * Format: `Ability:ResourceName`  e.g. `ViewAny:NewsModel`
     */
    private const CONTENT_RESOURCES = [
        'NewsModel',
        'PageModel',
        'ServiceModel',
        'TeamMemberModel',
        'EloquentOffice',
    ];

    private const STRUCTURAL_RESOURCES = [
        'HomeSection',
        'MenuItem',
    ];

    /** Abilities that constitute read-only access. */
    private const READ_ABILITIES = ['ViewAny', 'View'];

    /** All abilities generated for content resources by Shield. */
    private const MANAGER_ABILITIES = [
        'ViewAny',
        'View',
        'Create',
        'Update',
        'Delete',
        'DeleteAny',
        'ForceDelete',
        'ForceDeleteAny',
        'Restore',
        'RestoreAny',
        'Replicate',
        'Reorder',
    ];

    /** Abilities that constitute full content CRUD (no hard-delete variants). */
    private const EDITOR_ABILITIES = ['ViewAny', 'View', 'Create', 'Update', 'Delete'];

    public function run(): void
    {
        // Reset cached roles and permissions between runs (important for tests).
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        $requiredPermissionNames = $this->requiredPermissionNames();
        $existingPermissionNames = Permission::query()
            ->where('guard_name', 'web')
            ->whereIn('name', $requiredPermissionNames)
            ->pluck('name')
            ->all();
        $missingPermissionNames = array_values(array_diff($requiredPermissionNames, $existingPermissionNames));

        if ($missingPermissionNames !== []) {
            throw new \RuntimeException(sprintf(
                'Missing required permissions: %s. Run "php artisan shield:generate --all --panel=admin" before seeding roles.',
                implode(', ', $missingPermissionNames),
            ));
        }

        $this->seedSuperAdmin();
        $this->seedManager();
        $this->seedEditor();
        $this->seedViewer();
    }

    private function seedSuperAdmin(): void
    {
        $superAdmin = Role::firstOrCreate(['name' => 'super_admin', 'guard_name' => 'web']);

        // Assign ALL permissions (generated by shield:generate).
        $allPermissions = Permission::all();
        $superAdmin->syncPermissions($allPermissions);
    }

    private function seedManager(): void
    {
        $manager = Role::firstOrCreate(['name' => 'manager', 'guard_name' => 'web']);

        // Full CRUD on all content resources (all abilities Shield generates).
        $permissions = Permission::where(function ($query): void {
            foreach (self::CONTENT_RESOURCES as $resource) {
                $query->orWhere('name', 'like', "%:{$resource}");
            }
        })->get();

        $manager->syncPermissions($permissions);
    }

    private function seedEditor(): void
    {
        $editor = Role::firstOrCreate(['name' => 'editor', 'guard_name' => 'web']);

        // Content-only: ViewAny, View, Create, Update, Delete on content resources.
        // No structural resources (HomeSection, MenuItem), no Role management.
        $permNames = [];
        foreach (self::CONTENT_RESOURCES as $resource) {
            foreach (self::EDITOR_ABILITIES as $ability) {
                $permNames[] = "{$ability}:{$resource}";
            }
        }

        $permissions = Permission::whereIn('name', $permNames)->get();
        $editor->syncPermissions($permissions);
    }

    private function seedViewer(): void
    {
        $viewer = Role::firstOrCreate(['name' => 'viewer', 'guard_name' => 'web']);

        // Read-only: ViewAny + View on ALL resources (content + structural).
        $allResources = array_merge(self::CONTENT_RESOURCES, self::STRUCTURAL_RESOURCES);

        $permNames = [];
        foreach ($allResources as $resource) {
            foreach (self::READ_ABILITIES as $ability) {
                $permNames[] = "{$ability}:{$resource}";
            }
        }

        $permissions = Permission::whereIn('name', $permNames)->get();
        $viewer->syncPermissions($permissions);
    }

    /**
     * Return the permission names required by the role assignments below.
     *
     * @return list<string>
     */
    private function requiredPermissionNames(): array
    {
        $permissionNames = [];

        foreach (self::CONTENT_RESOURCES as $resource) {
            foreach (self::MANAGER_ABILITIES as $ability) {
                $permissionNames[] = "{$ability}:{$resource}";
            }
        }

        foreach (self::STRUCTURAL_RESOURCES as $resource) {
            foreach (self::READ_ABILITIES as $ability) {
                $permissionNames[] = "{$ability}:{$resource}";
            }
        }

        return $permissionNames;
    }
}
