<?php

declare(strict_types=1);

namespace Tests\Feature\Auth;

use App\Models\User;
use Database\Seeders\RolesAndPermissionsSeeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\PermissionRegistrar;

/**
 * Shared setup for role-based feature tests.
 *
 * Sets up the stub permission records that mirror what `shield:generate`
 * produces at runtime (format: `Ability:ResourceName`), then seeds the four
 * application roles with the correct permission subsets.
 *
 * Use in conjunction with RefreshDatabase so each test starts clean.
 */
trait RoleTestSetupTrait
{
    /** All resource identifiers as generated by Shield v4. */
    private const RESOURCE_NAMES = [
        'NewsModel',
        'PageModel',
        'ServiceModel',
        'TeamMemberModel',
        'EloquentOffice',
        'HomeSection',
        'MenuItem',
        'Role',
    ];

    /** All ability prefixes Shield v4 generates per resource. */
    private const ABILITY_NAMES = [
        'ViewAny',
        'View',
        'Create',
        'Update',
        'Delete',
        'DeleteAny',
        'ForceDelete',
        'ForceDeleteAny',
        'Restore',
        'RestoreAny',
        'Replicate',
        'Reorder',
    ];

    /**
     * Create stub permissions and seed roles/permissions.
     *
     * Must be called in setUp() after parent::setUp() and RefreshDatabase
     * has reset the DB.
     */
    protected function setUpRolesAndPermissions(): void
    {
        app()[PermissionRegistrar::class]->forgetCachedPermissions();

        foreach (self::RESOURCE_NAMES as $resource) {
            foreach (self::ABILITY_NAMES as $ability) {
                Permission::firstOrCreate([
                    'name' => "{$ability}:{$resource}",
                    'guard_name' => 'web',
                ]);
            }
        }

        $this->seed(RolesAndPermissionsSeeder::class);
    }

    /**
     * Create and persist a User with the given role pre-assigned.
     *
     * Relies on UserFactory::withRole() state.
     */
    protected function userWithRole(string $role): User
    {
        return User::factory()->withRole($role)->create();
    }
}
